---
abstract: 'Test Module for Alien::Base'
author:
  - 'Graham Ollis <plicease@cpan.org>'
  - 'Joel A. Berger <joel.a.berger@gmail.com>'
build_requires:
  Capture::Tiny: '0'
  ExtUtils::CBuilder: '0'
  IO::Socket::SSL: '1.56'
  Net::SSLeay: '1.49'
  Test2: '1.302015'
  Test2::Suite: '0.000030'
  Test2::V0: '0'
  Test::Alien: '0.05'
configure_requires:
  Alien::Base::ModuleBuild: '1.03'
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-Alien-DontPanic
provides:
  Acme::Alien::DontPanic:
    file: lib/Acme/Alien/DontPanic.pm
    version: '1.03'
requires:
  Alien::Base: '1.41'
  perl: '5.008001'
resources:
  IRC: irc://irc.perl.org/#native
  MailingList: https://groups.google.com/forum/#!forum/perl5-alien
  bugtracker: http://github.com/Perl5-Alien/Acme-Alien-DontPanic/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/Perl5-Alien/Acme-Alien-DontPanic
version: '1.03'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
